- hosts: all
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ec2-user/Deployment.yml
       ignore_errors: yes
     - name: delete old service
       command: kubectl delete -f /home/ec2-user/Service.yml
       ignore_errors: yes
     - name: create new deployment
       command: kubectl apply -f /home/ec2-user/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ec2-user/Service.yml
