kind: Deployment
apiVersion: apps/v1
metadata:
   name: devopst
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: devopst
   template:
      metadata:
        labels:
          app: devopst
      spec:
       containers:
        - name: devopst
          image: devopst/k8s-yt
          imagePullPolicy: Always
          ports:
          - containerPort: 80