kind: Service                             
apiVersion: v1
metadata:
  name: devopst
  labels:
    app: devopst
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: devopst                    
  type: LoadBalancer                   
