kind: Service                             
apiVersion: v1
metadata:
  name: devopst
  labels:
    app: devopst
spec:
  ports:
    - port: 8086                               
      targetPort: 3333                    
  selector:
    app: devopst                    
  type: LoadBalancer                   
